export const PRODUCT_LIST_QUERY = 'PRODUCT_LIST_QUERY';
export const PRODUCT_LIST_QUERY_V1 = 'PRODUCT_LIST_QUERY_V1';
export const PRODUCT_LIST_QUERY_V2 = 'PRODUCT_LIST_QUERY_V2';
export const BANNER_LIST_QUERY = 'BANNER_LIST_QUERY';
export const RANDOM_LIST_QUERY = 'RANDOM_LIST_QUERY';

export const TAGS_LIST_QUERY = 'TAGS_LIST_QUERY';

export const LOCATIONS_LIST_QUERY = 'LOCATIONS_LIST_QUERY';

export const COLLECTION_PRODUCT_LIST_QUERY = 'COLLECTION_PRODUCT_LIST_QUERY';
export const COLLECTION_LIST_QUERY = 'COLLECTION_LIST_QUERY';

export const CART_QUERY = 'CART_QUERY';
export const CART_ITEM_COUNT_QUERY = 'CART_ITEM_COUNT_QUERY';
